### DISCUSSION TITLE
你好，没看明白怎么使用反查和xmoji

### DISCUSSION THREAD

**Discussion by Attiv** [amorphobia/openfly#42] [问与答/Q&A]
我按照readme试了试，看了看您的方案 `https://github.com/amorphobia/my-rime-config`, 还是没弄明白xmoji 和反查怎么使用，麻烦可以详细讲解一下吗？可以和这个库已经用吗https://github.com/brglng/rime-xhup
谢谢

**Comment by amorphobia** [comment]
xmoji 其实搞得不太好，只是我自己用用，其实就相当于外挂了一个 emoji 的词库

反查的话，成功部署后，跟官方的小鹤音形一样，用反撇键就可以了，主要就是 openfly_reverse.schema.yaml，openfly_reverse.dict.yaml 这两个文件，以及主方案（openfly.schema.yaml）里面的

```
# 这两行告诉 rime, 本方案依赖于 openfly_reverse 这个方案，所以在部署的时候才会将其一起部署
  dependencies:
    - openfly_reverse
```

```
  translators:
    - punct_translator
    - table_translator
    - lua_translator@openfly_date_translator
    - lua_translator@openfly_time_translator
    - lua_translator@openfly_shortcut_translator
    - reverse_lookup_translator # 这一行告诉 rime 要启用反查翻译器
    - history_translator@history
```

以及

```
# 这几行告诉 rime, 反查的词典名字叫 openfly_reverse
reverse_lookup:
  dictionary: openfly_reverse
  comment_format:
    - xform/ / /
```

还有

```
# 这几行告诉 rime, 什么时候是在反查，也就是那个正则表达式
recognizer:
  import_preset: default
  patterns:
    uppercase: ""
    reverse_lookup: "[a-z`]*`+[a-z`]*"
    punct: ""
```
